Repository 1up-lab/OneupFlysystemBundle, pull requests merged in 2023-08, with the labels that each got.

#283 Permissions configuration for sftp adapter
  src/DependencyInjection/Factory/Adapter/SftpFactory.php
Labels: enhancement

#284 Add support for selecting visibilityHandler class
  src/DependencyInjection/Factory/Adapter/GoogleCloudStorageFactory.php
Labels: enhancement

#282 Be able to configure $lazyRootCreation of LocalFilesystemAdapter
  doc/adapter_local.md
  src/DependencyInjection/Factory/Adapter/LocalFactory.php
  src/Resources/config/adapters.xml
Labels: enhancement

#285 Revert "supports env variables in configuration (#277)"
  doc/index.md
  src/DependencyInjection/OneupFlysystemExtension.php
Labels: bug, BC break

#276 Remove cache property from documentation
  doc/filesystem_create.md
Labels: question, documentation
